{
 "title": "Nightscout data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "current",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ns\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openaps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bg\" )\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ r with \n    _value: r._value/18.0,\n    _measurement: \"\"\n    }))"
    }
   ]
  },
  {
   "title": "BG",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ns\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openaps\")\n  |> filter(fn: (r) => r._value > 0)\n  |> filter(fn: (r) => r[\"_field\"] == \"bg\" \n    or r[\"_field\"] == \"iob\"\n    or r[\"_field\"] == \"bolus\" \n    or r[\"_field\"] == \"insulin_req\"\n    or r[\"_field\"] == \"bg\" \n    or r[\"_field\"] == \"isf\" \n    or r[\"_field\"] == \"target_bg\"\n    or r[\"_field\"] == \"activity\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ r with \n    _field: if r._field == \"bolus\" then \"bolus smb\" else r._field,\n    _value: if r._field == \"bg\" or r._field == \"target_bg\" then r._value/18.0 else if r._field == \"activity\" then r._value*500.0 else r._value,\n    _measurement: \"\"\n    }))"
    },
    {
     "query": "from(bucket: \"ns\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"treatments\")\n  |> filter(fn: (r) => r[\"type\"] == \"bolus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bolus\")\n  |> filter(fn: (r) => r[\"smb\"] == \"false\")\n  |> drop(columns: [\"smb\", \"type\"])\n  |> map(fn: (r) => ({ r with _measurement: \"\" }))"
    },
    {
     "query": "from(bucket: \"ns\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"treatments\")\n  |> filter(fn: (r) => r[\"type\"] == \"tbs\" and r[\"_field\"] == \"percent\")\n  |> map(fn: (r) => ({ _time: r._time, \"basal\": (r._value + 100)*(-1)}))"
    }
   ]
  },
  {
   "title": "Predictions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "alias": "pred_cob",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "openaps",
     "query": "SELECT \"pred_cob\"  / 18.0 FROM \"ns\".\"openaps\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pred_cob" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 18.0" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "openaps",
     "select": [
      [
       { "params": [ "pred_iob" ], "type": "field" },
       { "params": [ " / 18.0" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "pred_uam",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "openaps",
     "query": "SELECT \"pred_uam\"  / 18.0 FROM \"ns\".\"openaps\" WHERE $timeFilter AND \"pred_uam\" > 39",
     "select": [
      [
       { "params": [ "pred_uam" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ " / 18.0" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "time in range",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ns\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openaps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bg\")\n  |> keep(columns: [\"_value\"])\n  |> map(fn: (r) => ({_value: r._value, label: if r._value < 70 then \"low\" else if r._value < 180 then \"normal\" else \"high\" }))\n  |> group(columns: [\"label\"])\n  |> count()\n  |> group()"
    }
   ]
  },
  {
   "title": "cob",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"ns\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openaps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cob\" or r[\"_field\"] == \"cr\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ r with _measurement: \"\" }))"
    }
   ]
  },
  {
   "title": "Еда",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"ns\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"treatments\")\n  |> filter(fn: (r) => r[\"_field\"] == \"carbs\" or r[\"_field\"] == \"notes\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> map(fn: (r) => ({ time: time(v:r._time), carbs: r.carbs, notes: r.notes }))"
    }
   ]
  },
  {
   "title": "dev",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 3, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"ns\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openaps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dev\" or r[\"_field\"] == \"cob\")\n  |> aggregateWindow(every: 5m, fn: last, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _measurement: \"\", is_cob : if r.cob > 0 then 1 else 0, _value: r.dev }))\n  |> filter(fn: (r) => r.is_cob <= 0)\n  |> map(fn: (r) => ({ _time: r._time, dev: r.dev }))"
    },
    {
     "query": "from(bucket: \"ns\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openaps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dev\" or r[\"_field\"] == \"cob\")\n  |> aggregateWindow(every: 5m, fn: last, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _measurement: \"\", is_cob : if r.cob > 0 then 1 else 0, _value: r.dev }))\n  |> filter(fn: (r) => r.is_cob > 0)\n  |> map(fn: (r) => ({ _time: r._time, dev_cob: r.dev }))"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "IOB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"ns\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openaps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"iob\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"ns\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openaps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"insulin_req\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "BG",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "openaps",
     "query": "SELECT \"bg\"  / 18.0 FROM \"ns\".\"openaps\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "bg" ], "type": "field" },
       { "params": [ " / 18.0" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "openaps",
     "select": [
      [
       { "params": [ "iob" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "openaps",
     "select": [
      [
       { "params": [ "insulin_req" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "openaps",
     "select": [
      [
       { "params": [ "bolus" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "BG",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"ns\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"treatments\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tbs\")\n  |> map(fn: (r) => ({ r with \n    _measurement: \"\"\n    }))"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } }
 ]
}